// <auto-generated />
namespace isuuetracker.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class FK_Additions : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FK_Additions));
        
        string IMigrationMetadata.Id
        {
            get { return "202002270935380_FK_Additions"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
